#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
# ==========================================

EMAIL="youremailaddress@example.com"
if [[ ${1+x} ]]; then
    EMAIL=$1;
fi

IP=$(wget -qO- ipinfo.io/ip);
date=$(date +"%Y-%m-%d")
clear
echo "Create Backup"
now=$(date +"%Y_%m_%d_%H_%M_%S")
cd /root
mkdir /root/tmp_backup_$now
cp /etc/passwd tmp_backup_$now/
cp /etc/group tmp_backup_$now/
cp /etc/shadow tmp_backup_$now/
cp /etc/gshadow tmp_backup_$now/
cd /root
zip -r server_backup_$now.zip /root/tmp_backup_$now 
sleep 1
rm -rf /root/tmp_backup_$now
echo "Backup File $now." | mutt -a "/root/server_backup_$now.zip" -s "Backup File $now" -- $EMAIL
echo -e "
Detail Backup 
==================================
IP VPS        : $IP
Directory     : /root/server_backup_$now.zip
Email         : $EMAIL
Date          : $date
==================================
"
